### ISSUE TITLE
Fetch data from Tweets2011 Collection

### ISSUE THREAD

**Issue by imgarylai** [lintool/twitter-tools#54]
Hello, 

I'm trying to fetch the Tweets2011 according to the wiki page: https://github.com/lintool/twitter-tools/wiki/Tweets2011-Collection#fetching-a-status-block 

I have a question regarding the example command: 

```
sh target/appassembler/bin/AsyncHTMLStatusBlockCrawler \
   -data 20110123/20110123-000.dat -output json/20110123-000.json.
```

I got `20110123/20110123-000.dat does not exist!` while running this command. 

Where can I find those `.dat` files? I could not find any page that describes those files.

**Comment by isoboroff** [comment]
See https://trec.nist.gov/data/tweets/

**Comment by imgarylai** [comment]
Hello, 

Thanks for you reply. I created this pull request was because I followed the instruction of the link you gave to me, but I was asked to this repos to use this tool to fetch the datasets. 

I already sent an email with the `TREC 2011 Microblog Dataset Usage Agreement` with all required information to the email.  I got the response, but the url, username and password didn't works. It showed I was unauthorized. 

Then I asked  why the url didn't work? The response told me to visit this repo. It is like an infinite loop. 

I can send the email again, but please tell me **what I missed** at least. I have been asked to come to repo in every responses.

**Comment by isoboroff** [comment]
Contact me at ian dot soboroff at nist dot gov and we'll get this sorted out.  It's not a repo issue, it looks like a communication issue on our end.
